# Generated by Django 4.1.5 on 2023-01-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('anuncio', models.CharField(max_length=400)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('responsavel', models.CharField(max_length=40)),
                ('celular', models.IntegerField(max_length=11)),
                ('cidade', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=80)),
                ('categoria', models.CharField(choices=[('EMP', 'Empregos'), ('IMO', 'Imóveis'), ('AUT', 'Automóveis'), ('SER', 'Serviços'), ('PER', 'Perdidos'), ('OUT', 'Outros')], max_length=3)),
            ],
        ),
    ]
